src/Entity/Project.php
<?php

namespace App\Entity;

use App\Repository\ProjectRepository;
use DateTimeInterface;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * @ORM\Entity(repositoryClass=ProjectRepository::class)
 * @Vich\Uploadable
 */
class Project
{
   /**
    * @ORM\Id
    * @ORM\GeneratedValue
    * @ORM\Column(type="integer")
    */
   private $id;

   /**
    * @ORM\Column(type="string", length=255)
    * @Assert\Length(
    *    min=3, minMessage="Le nom du projet est trop court, {{ limit }} caractères minimum",
    *    max=80, maxMessage="Le nom du projet est trop long, {{ limit }} caractères maximum"
    * )
    */
   private $name;

   /**
    * @ORM\Column(type="text")
    */
   private $description;

   /**
    * @ORM\Column(type="string", length=255, nullable=true)
    * @Assert\Regex(
    *    pattern="/[a-zA-Z0-9._-]{2,256}\.[a-z]{2,4}\b([a-zA-Z0-9-\/]*)/",
    *    message="Votre url n'est pas valide"
    * )
    */
   private $link;

   /**
    * @ORM\Column(type="datetime")
    * @Assert\NotBlank()
    */
   private $createdAt;

   /**
    * @ORM\OneToMany(targetEntity=Images::class, mappedBy="project")
    */
   private $picture;

   /**
    * @ORM\ManyToMany(targetEntity=Technology::class, inversedBy="projects")
    */
   private $technology;

   /**
    * @ORM\Column(type="string", length=255)
    */
   private $slug;

   /**
    * @ORM\Column(type="string", length=255)
    * @Assert\NotBlank()
    */
   private $frame;

   /**
    * @ORM\Column(type="string", length=255)
    * @Assert\NotBlank()
    * @Assert\Length(
    *    max=255,
    *    maxMessage="Vous ne devez pas excéder {{ limit }} caractères"
    * )
    */
   private $short_description;

   public function __construct()
   {
      $this->picture = new ArrayCollection();
      $this->technology = new ArrayCollection();
   }

   public function getId(): ?int
   {
      return $this->id;
   }

   public function getName(): ?string
   {
      return $this->name;
   }

   public function setName(string $name): self
   {
      $this->name = $name;

      return $this;
   }

   public function getDescription(): ?string
   {
      return $this->description;
   }

   public function setDescription(string $description): self
   {
      $this->description = $description;

      return $this;
   }

   public function getLink(): ?string
   {
      return $this->link;
   }

   public function setLink(?string $link): self
   {
      $this->link = $link;

      return $this;
   }

   public function getCreatedAt(): ?DateTimeInterface
   {
      return $this->createdAt;
   }

   public function setCreatedAt(DateTimeInterface $createdAt): self
   {
      $this->createdAt = $createdAt;

      return $this;
   }

   /**
    * @return Collection|Images[]
    */
   public function getPicture(): Collection
   {
      return $this->picture;
   }

   public function addPicture(Images $picture): self
   {
      if (!$this->picture->contains($picture)) {
         $this->picture[] = $picture;
         $picture->setProject($this);
      }

      return $this;
   }

   public function removePicture(Images $picture): self
   {
      if ($this->picture->removeElement($picture)) {
         // set the owning side to null (unless already changed)
         if ($picture->getProject() === $this) {
            $picture->setProject(null);
         }
      }

      return $this;
   }

   /**
    * @return Collection|Technology[]
    */
   public function getTechnology(): Collection
   {
      return $this->technology;
   }

   public function addTechnology(Technology $technology): self
   {
      if (!$this->technology->contains($technology)) {
         $this->technology[] = $technology;
      }

      return $this;
   }

   public function removeTechnology(Technology $technology): self
   {
      $this->technology->removeElement($technology);

      return $this;
   }

   public function getSlug(): ?string
   {
      return $this->slug;
   }

   public function setSlug(string $slug): self
   {
      $this->slug = $slug;

      return $this;
   }

   public function getFrame(): ?string
   {
      return $this->frame;
   }

   public function setFrame(string $frame): self
   {
      $this->frame = $frame;

      return $this;
   }

   public function getShortDescription(): ?string
   {
      return $this->short_description;
   }

   public function setShortDescription(string $short_description): self
   {
      $this->short_description = $short_description;

      return $this;
   }
}

templates/pages/contact.html.twig
{% extends 'base.html.twig' %}

{% block title 'Contact' %}

{% block body %}
   <div class="wrapper-main">
      <div class="contact">
         <div class="image">
            <img src="{{ asset('images/image-contact.png') }}" alt="image abstraite du formulaire">
         </div>
         <div class="form-contact">
            <h1 class="title">Contact</h1>
            <form action="{{ path('contact') }}" method="post" class="form">
               {{ form_start(form) }}
               <div class="form-body">
                  <div class="form-group">
                     <div class="form-floating">
                        {{ form_widget(form.firstname, {
                           'attr': {'class': 'form-control required', 'id': 'floatingFirstname', 'placeholder': ' ', 'resuired': 'true'}
                        }) }}
                        {{ form_label(form.firstname, null, {'label': 'Nom'}) }}
                     </div>
                     <div class="form-floating">
                        {{ form_widget(form.lastname, {
                           'attr': {'class': 'form-control required', 'id': 'floatingLastname', 'placeholder': ' ', 'resuired': 'true'}
                        }) }}
                        {{ form_label(form.lastname, null, {'label': 'Prénom'}) }}
                     </div>
                  </div>
                  <div class="form-group">
                     <div class="form-floating">
                        {{ form_widget(form.email, {
                           'attr': {'class': 'form-control required', 'id': 'floatingEmail', 'placeholder': ' ', 'resuired': 'true'}
                        }) }}
                        {{ form_label(form.email, null, {'label': 'Email'}) }}
                     </div>
                  </div>
                  <div class="form-group">
                     <div class="form-floating">
                        {{ form_widget(form.message, {
                           'attr': {'class': 'form-control required', 'id': 'floatingMessage', 'placeholder': ' ', 'resuired': 'true'}
                        }) }}
                        {{ form_label(form.message, null, {'label': 'Message'}) }}
                     </div>
                  </div>
                  <div class="form-group action">
                     <button class="btn btn-primary">
                        Envoyer
                     </button>
                  </div>
               </div>
               {{ form_end(form) }}
            </form>
         </div>
      </div>
   </div>
{% endblock %}

{% block stylesheets %}
   {{ parent() }}
   {{ encore_entry_link_tags('contact') }}
{% endblock %}

templates/pages/index.html.twig
{% extends 'base.html.twig' %}

{% block title 'Accueil' %}

{% block body %}
   <header class="header">
      <div class="header-title">
         <h3 class="welcome">Bonjour, je suis</h3>
         <h1 class="fullName">{{ information.firstname }} {{ information.lastname }}</h1>
         <h5 class="job my-2">{{ information.job }}</h5>
         <p class="mt-5">
            <a href="#projects" class="btn btn-primary">Voir mes réalisations</a>
         </p>
      </div>
      <img src="{{ asset('images/test.svg') }}"
           alt="{{ information.lastname }}{{ information.firstname }}">
   </header>

   {% include 'pages/information.html.twig' %}
   {% include 'pages/skills.html.twig' %}
   {% include 'pages/project.html.twig' %}
{% endblock %}

templates/pages/information.html.twig
<div class="information">
   <img src="{{ asset('images/bg-info.svg') }}" alt="background angle" class="bg bg-top-right">
   <img src="{{ asset('images/bg-info.svg') }}" alt="background angle" class="bg bg-bottom-left">
   <div class="presentation">
      <p>{{ information.description | nl2br }}</p>
      <a class="btn btn-primary mt-3" href="#">Me contacter</a>
   </div>
</div>

templates/pages/project.html.twig
<section class="section-realisation" id="projects">
   <div class="wrapper">
      {% for project in projects %}
         <a class="link-project" href="{{ path('project_detail', { 'slug': project.slug | lower }) }}"
            title="{{ project.name }}">
            <div class="card-realisation card-{{ loop.index }}">
               {% for image in project.picture %}
                  {% if image.isHighlight %}
                     <img src="{{ vich_uploader_asset(image, 'imageFile') }}" class=""
                          alt="{{ project.link|default(project.name) }}">
                  {% endif %}
               {% endfor %}
               <div class="hover-effect">
                  <div class="hover-effect-body">
                     <h5 class="card-title">{{ project.name }}</h5>
                  </div>
               </div>
            </div>
         </a>
      {% endfor %}
   </div>
   <div class="cta-project">
      <a class="btn btn-outline-primary" href="{{ path('project_list') }}">Toutes mes réalisations</a>
   </div>
</section>

templates/pages/projectDetail.html.twig
{% extends 'base.html.twig' %}

{% block title project.name %}

{% block body %}
   <div class="wrapper-main">
      <div class="wrapper-project">
         <h1>{{ project.name }}</h1>
         <div class="wrapper-content-project">
            <div class="image-container">
               {% for image in project.picture %}
                  <button type="button" class="btn-modal {{ image.isHighlight ? 'highlight' : '' }}"
                          data-bs-toggle="modal" data-bs-target="#modal-slide">
                     <img src="{{ vich_uploader_asset(image, 'imageFile') }}" alt="{{ project.name }}">
                  </button>
               {% endfor %}
            </div>
            <div class="wc-section">
               <div class="wc-info">
                  <h3>Informations générales</h3>
                  <table>
                     <tr>
                        <th>Développement</th>
                        <td>
                           {{ project.createdAt | date("m/Y") }}
                        </td>
                     </tr>
                     <tr>
                        <th>Cadre</th>
                        <td>{{ project.frame }}</td>
                     </tr>
                     <tr>
                        <th>Technologies</th>
                        <td>
                           {% for tech in project.technology %}
                              <span>
                                 <img src="{{ vich_uploader_asset(tech.image, 'imageFile') }}"
                                      class="tech"
                                      alt="{{ project.name }}">
                              </span>
                           {% endfor %}
                        </td>
                     </tr>
                  </table>

               </div>
               <div class="wc-resume">
                  <h3>Résumé</h3>
                  <p>{{ project.description | raw | nl2br }}</p>
                  {% if project.link != null %}
                     <div class="wc-footer">
                        <a class="btn btn-primary" href="https://{{ project.link }}" target="_blank"
                           title="{{ project.name }}">
                           Visiter le site
                        </a>
                     </div>
                  {% endif %}
               </div>
            </div>
         </div>
      </div>
   </div>


   <div class="modal fade" id="modal-slide" tabindex="-1" aria-labelledby="exampleModalLabel"
        aria-hidden="true">
      <div class="modal-dialog">
         <div class="modal-content">
            <div id="carouselProject" class="carousel slide" data-bs-ride="carousel">
               <div class="carousel-inner">
                  {% for image in project.picture %}
                     <div class="carousel-item {{ loop.index == 1 ? 'active' : '' }}">
                        <img src="{{ vich_uploader_asset(image, 'imageFile') }}"
                             class="{{ image.isHighlight ? 'highlight' : 'secondary-img' }} d-block w-100"
                             alt="{{ project.name }}">
                     </div>
                  {% endfor %}
               </div>
               <button class="carousel-control-prev" type="button" data-bs-target="#carouselProject"
                       data-bs-slide="prev">
                  <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                  <span class="visually-hidden">Previous</span>
               </button>
               <button class="carousel-control-next" type="button" data-bs-target="#carouselProject"
                       data-bs-slide="next">
                  <span class="carousel-control-next-icon" aria-hidden="true"></span>
                  <span class="visually-hidden">Next</span>
               </button>
            </div>
         </div>
      </div>
   </div>

{% endblock %}

{% block stylesheets %}
   {{ parent() }}
   {{ encore_entry_link_tags('project') }}
{% endblock %}

templates/pages/projectList.html.twig
{% extends 'base.html.twig' %}

{% block title 'Mes réalisations' %}

{% block body %}

   <div class="wrapper-main">
      <div class="projects-list">
         <h1>Réalisations</h1>
         <div class="project-main">
            {% for project in projects %}
               <div class="project-content">
                  <div class="project-content-card">
                     <div class="card-project-header">
                        {% for image in project.picture %}
                           {% if image.isHighlight %}
                              <img src="{{ vich_uploader_asset(image, 'imageFile') }}" class=""
                                   alt="{{ project.link|default(project.name) }}">
                           {% endif %}
                        {% endfor %}
                     </div>
                     <div class="card-project-main">
                        <h5 class="card-project-title">{{ project.name }}</h5>
                        <div class="card-project-tech">
                           {% for tech in project.technology %}
                              {% if loop.index != 1 %} - {% endif %}
                              {{ tech.name }}

                           {% endfor %}
                        </div>
                        <div
                            class="card-project-body">
                           {{ project.shortDescription | length > 0 ? project.shortDescription : 'Aucune description' }}
                        </div>
                        <div class="card-project-footer">
                           <a class="btn btn-sm btn-outline-primary"
                              href="{{ path('project_detail', { 'slug': project.slug | lower }) }}">En
                              savoir plus</a>
                        </div>
                     </div>
                  </div>
               </div>
            {% endfor %}
         </div>
      </div>
   </div>

{% endblock %}

{% block stylesheets %}
   {{ parent() }}
   {{ encore_entry_link_tags('project-list') }}
{% endblock %}

templates/pages/skills.html.twig
<div class="skills" id="skills">
   {% for category in categories %}
      <div class="card card-category">

         <div class="card-header-category">
            {% for tech in technologies %}
               {% if tech.category.name == category.name %}
                  <img src="{{ vich_uploader_asset(tech.image, 'imageFile') }}" alt="{{ tech.image.name }}"
                       title="{{ tech.image.name }}">
               {% endif %}
            {% endfor %}
         </div>
         <div class="card-title-category">
            <h5>{{ category.name }}</h5>
         </div>
         <div class="card-text-category">
            {{ category.description }}
         </div>

      </div>
   {% endfor %}
</div>