src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 */
class User implements UserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }
}

templates/base.admin.html.twig
<!DOCTYPE html>
<html lang="fr">
<head>
   <meta charset="UTF-8">
   <meta name="viewport"
         content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
   <meta http-equiv="X-UA-Compatible" content="ie=edge">
   <title>{% block title %}{{ app.user.username }}{% endblock %} | Admin</title>
   <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet"/>
   <script src="https://cdn.tiny.cloud/1/no-api-key/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
   {% block stylesheets %}
      {{ encore_entry_link_tags('app') }}
      {{ encore_entry_link_tags('admin') }}
   {% endblock %}
</head>
<body>
<div class="main">


   {% for label, messages in app.flashes %}
      {% for message in messages %}
         <div role="alert" aria-live="assertive" aria-atomic="true" class="toast {{ label }}">
            <div class="toast-header">
               <strong class="me-auto">{{ label }}</strong>
            </div>
            <div class="toast-body">{{ message }}</div>
         </div>
      {% endfor %}
   {% endfor %}


   {% include 'parts/_menu.admin.html.twig' %}
   {% block body %}{% endblock %}
   {% block javascripts %}
      {{ encore_entry_script_tags('app') }}
   {% endblock %}
   <script src="https://kit.fontawesome.com/bfe9f51c30.js" crossorigin="anonymous"></script>
   <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
</div>
</body>
</html>

templates/base.html.twig
<!DOCTYPE html>
<html lang="fr">
<head>
   <meta charset="UTF-8">
   <meta name="viewport"
         content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
   <meta http-equiv="X-UA-Compatible" content="ie=edge">
   <title>{% block title %}{{ app.user.email }}{% endblock %} | Déwi Dierick - Développeur web mobile</title>
   {% block stylesheets %}
      {{ encore_entry_link_tags('app') }}
   {% endblock %}
</head>
<body>

{% for label, messages in app.flashes %}
   {% for message in messages %}
      <div role="alert" aria-live="assertive" aria-atomic="true" class="toast {{ label }}" id="toast">
         <div class="toast-header">
            <strong class="me-auto">{{ label }}</strong>
         </div>
         <div class="toast-body">{{ message }}</div>
      </div>
   {% endfor %}
{% endfor %}
<div class="main">
   {% include 'parts/_menu.html.twig' %}
   {% block body %} {% endblock %}
   {% include 'parts/_footer.html.twig' %}
   {% block javascripts %}
      {{ encore_entry_script_tags('app') }}
   {% endblock %}
</div>
</body>
</html>