src/Entity/Information.php
<?php

namespace App\Entity;

use App\Repository\InformationRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=InformationRepository::class)
 */
class Information
{
   /**
    * @ORM\Id
    * @ORM\GeneratedValue
    * @ORM\Column(type="integer")
    */
   private $id;

   /**
    * @ORM\Column(type="string", length=255)
    * @Assert\Length(
    *    min=3, minMessage="Votre nom est trop court, {{ limit }} caractères minimum",
    *    max=80, maxMessage="Votre nom est trop long, {{ limit }} caractères maximum"
    * )
    */
   private $lastname;

   /**
    * @ORM\Column(type="string", length=255)
    * @Assert\Length(
    *    min=3, minMessage="Votre prénom est trop court, {{ limit }} caractères minimum",
    *    max=80, maxMessage="Votre prénom est trop long, {{ limit }} caractères maximum"
    * )
    */
   private $firstname;

   /**
    * @ORM\Column(type="string", length=255)
    * @Assert\NotBlank(
    *    message="Ce champs est requis"
    * )
    * @Assert\Email(
    *    message="Votre email n'est pas valide"
    * )
    */
   private $email;

   /**
    * @ORM\Column(type="string", length=255)
    * @Assert\NotBlank(
    *    message="Ce champs est requis"
    * )
    * @Assert\Length(
    *    max=80, maxMessage="Votre job est trop long, {{ limit }} caractères maximum"
    * )
    */
   private $job;

   /**
    * @ORM\Column(type="string", nullable=true)
    * @Assert\Regex(
    *    pattern="/^0[0-9]{1}\.[0-9]{2}\.[0-9]{2}\.[0-9]{2}\.[0-9]{2}$/",
    *    message="Votre numéro de téléphone n'est pas valide"
    * )
    */
   private $phone;

   /**
    * @ORM\OneToOne(targetEntity=Images::class, cascade={"persist", "remove"})
    * @Assert\NotBlank()
    */
   private $image;

   /**
    * @ORM\Column(type="text")
    */
   private $description;

   /**
    * @ORM\Column(type="string", length=255)
    */
   private $city;

   /**
    * @ORM\Column(type="string", length=255)
    */
   private $postal_code;

   public function getId(): ?int
   {
      return $this->id;
   }

   public function getLastname(): ?string
   {
      return $this->lastname;
   }

   public function setLastname(string $lastname): self
   {
      $this->lastname = $lastname;

      return $this;
   }

   public function getFirstname(): ?string
   {
      return $this->firstname;
   }

   public function setFirstname(string $firstname): self
   {
      $this->firstname = $firstname;

      return $this;
   }

   public function getEmail(): ?string
   {
      return $this->email;
   }

   public function setEmail(string $email): self
   {
      $this->email = $email;

      return $this;
   }

   public function getJob(): ?string
   {
      return $this->job;
   }

   public function setJob(string $job): self
   {
      $this->job = $job;

      return $this;
   }

   public function getPhone(): ?string
   {
      return $this->phone;
   }

   public function setPhone(?string $phone): self
   {
      $this->phone = $phone;

      return $this;
   }

   public function getImage(): ?Images
   {
      return $this->image;
   }

   public function setImage(?Images $image): self
   {
      $this->image = $image;

      return $this;
   }

   public function getDescription(): ?string
   {
      return $this->description;
   }

   public function setDescription(string $description): self
   {
      $this->description = $description;

      return $this;
   }

   public function getCity(): ?string
   {
       return $this->city;
   }

   public function setCity(string $city): self
   {
       $this->city = $city;

       return $this;
   }

   public function getPostalCode(): ?string
   {
       return $this->postal_code;
   }

   public function setPostalCode(string $postal_code): self
   {
       $this->postal_code = $postal_code;

       return $this;
   }
}

templates/parts/_card.html.twig
{% set route = route | default(null) %}

<div class="col">
   {% if route is not null %}
   <a href="{{ path(route) }}" title="{{ title }}">
      {% endif %}
      <div class="card border-primary mb-3">
         <div class="card-header">{{ title }}</div>
         <div class="card-body text-primary">
            <p class="card-text h5">{{ content }}</p>
         </div>
      </div>
      {% if route is not null %}
   </a>
   {% endif %}
</div>

templates/parts/_footer.html.twig
<footer class="footer">
   <div class="container">
      <div class="social">
         <p>
         <h5>{{ information.lastname }} {{ information.firstname }}</h5>
         {{ information.job }}<br/>
         {{ information.postalCode }} {{ information.city }}<br/>
         {{ information.phone }}
         </p>
      </div>
      <div class="social">
         {% for social in socials %}
            <a href="https://{{ social.link }}" class="social-link" target="_blank" title="{{ social.name }}">
               <img src="{{ vich_uploader_asset(social.image, 'imageFile') }}" alt="{{ social.name }}">
            </a>
         {% endfor %}
      </div>
   </div>
</footer>

templates/parts/_menu.admin.html.twig
<nav class="navbar navbar-expand-lg">
   <div class="container">
      <a class="navbar-brand" href="/">Déwi Dierick</a>
      <div class="collapse navbar-collapse">
         <ul class="navbar-nav ms-auto mb-lg-0">
            <a class="nav-link" href="{{ path('app_logout') }}"><span class="mx-2"><i class="mr-2 fas fa-power-off"></i></span>Déconnexion</a>
         </ul>
      </div>
   </div>
</nav>

templates/parts/_menu.admin.mobile.html.twig
<nav class="navbar-mobile-bottom d-md-none">
   <div class="nav-menu">
      <span><a href="{{ path('admin') }}" title="Accueil admin"><i class="fas fa-home"></i></a></span>
      <span><a class="target-menu" href="" title="Dérouler le menu"><i class="fas fa-bars"></i></a></span>
      <span><a href="{{ path('home') }}" title="Retour au site public"><i class="fas fa-globe"></i></a></span>
   </div>
   <ul class="menu-target">
      <li class="item-menu"><a href="{{ path('information_index') }}" title="Mon compte">
            <i class="fas fa-user me-2"></i>Mon compte</a>
      </li>
      <li class="item-menu"><a href="" title="Formations">
            <i class="fas fa-graduation-cap me-2"></i>Formations</a>
      </li>
      <li class="item-menu"><a href="" title="Expériences">
            <i class="fas fa-briefcase me-2"></i>Expériences</a>
      </li>
      <li class="item-menu"><a href="{{ path('technology_index') }}" title="Technologies">
            <i class="fas fa-microchip me-2"></i>Technologies</a>
      </li>
      <li class="item-menu"><a href="{{ path('images_index') }}" title="Imagethèque">
            <i class="fas fa-image me-2"></i>Imagethèque</a>
      </li>
      <li class="item-menu"><a href="{{ path('social_index') }}" title="Réseaux">
            <i class="fas fa-comments me-2"></i>Réseaux</a>
      </li>
      <li class="item-menu"><a href="{{ path('project_index') }}" title="Projets">
            <i class="fas fa-project-diagram me-2"></i>Projets</a>
      </li>
      <li class="item-menu disconnect" title="Se déconnecter">
         <a href="{{ path('app_logout') }}" title="Se déconnecter">
            <i class="fas fa-power-off"></i>
            Déconnecter
         </a>
      </li>
   </ul>
</nav>

templates/parts/_menu.aside.html.twig
<aside class="aside d-none d-md-block">
   <nav>
      <ul class="menu-column">
         <li class="menu-column-item {{ class == 'dashboard' ? 'active' : '' }}">
            <a href="{{ path('admin') }}"><i class="fas fa-home"></i>Dashboard</a>
         </li>
         <li class="menu-column-item {{ class == 'account' ? 'active' : '' }}">
            <a href="{{ path('information_index') }}"><i class="fas fa-user"></i>Mon compte</a>
         </li>
         <li class="menu-column-item {{ class == 'training' ? 'active' : '' }}">
            <a href="#"><i class="fas fa-graduation-cap"></i>Formations</a>
         </li>
         <li class="menu-column-item {{ class == 'experience' ? 'active' : '' }}">
            <a href="#"><i class="fas fa-briefcase"></i>Expériences</a>
         </li>
         <li class="menu-column-item {{ class == 'technologies' ? 'active' : '' }}">
            <a href="{{ path('technology_index') }}"><i class="fas fa-microchip"></i>Technologies</a>
         </li>
         <li class="menu-column-item {{ class == 'image' ? 'active' : '' }}">
            <a href="{{ path('images_index') }}"><i class="fas fa-image"></i>Imagethèque</a>
         </li>
         <li class="menu-column-item {{ class == 'reseau' ? 'active' : '' }}">
            <a href="{{ path('social_index') }}"><i class="fas fa-comments"></i>Réseaux</a>
         </li>
         <li class="menu-column-item {{ class == 'project' ? 'active' : '' }}">
            <a href="{{ path('project_index') }}"><i class="fas fa-project-diagram"></i>Projets</a>
         </li>
         <li class="menu-column-item {{ class == 'skill' ? 'active' : '' }}">
            <a href="{{ path('categories_index') }}"><i class="fas fa-tags"></i>Catégories</a>
         </li>
      </ul>
   </nav>
</aside>

templates/parts/_menu.html.twig
<nav class="navbar navbar-expand-lg navbar-light bg-light mb-5" id="nav-public">
   <div class="container">
      <a class="navbar-brand" id="brand" href="/">Déwi Dierick</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown"
              aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
         <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
         <ul class="navbar-nav ms-auto">
            <li class="nav-item">
               <a class="nav-link" href="{{ path('project_list') }}">Réalisations</a>
            </li>
            <li class="nav-item">
               <a class="nav-link" href="{{ path('contact') }}">Me contacter</a>
            </li>
            {% if app.user %}
               <li class="nav-item admin">
                  <a class="nav-link" href="{{ path('admin') }}">Administration</a>
               </li>
            {% endif %}
         </ul>
      </div>
   </div>
</nav>